/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saxGUI;

import ClaseDOM.DOM;
import claseCoche.Coche;
import claseCoche.CocheHandler;
import claseSAX.Sax;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;
import lecturaDOMSinParametrosGUI.LecturaSinParametros;
import mainGUI.DOMGUI;
import org.xml.sax.SAXException;

/**
 *
 * @author oscartabora
 */
public class SAXGUI extends javax.swing.JFrame {

    /**
     * Creates new form SAXGUI
     */
    public SAXGUI() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jb_abrir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_area = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        tf_rutaa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tb_inicio = new javax.swing.JButton();
        tb_cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_abrir.setText("Abrir Archivo");
        jb_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_abrirActionPerformed(evt);
            }
        });
        jPanel1.add(jb_abrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 120, 40));

        jt_area.setColumns(20);
        jt_area.setRows(5);
        jScrollPane1.setViewportView(jt_area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 780, 280));

        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Abrir ruta del archivo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 150, 20));

        tf_rutaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rutaaActionPerformed(evt);
            }
        });
        jPanel1.add(tf_rutaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 270, 40));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Lectura XML con SAX");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 220, -1));

        tb_inicio.setText("Inicio");
        tb_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_inicioActionPerformed(evt);
            }
        });
        jPanel1.add(tb_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 110, 30));

        tb_cerrar.setText("Cerrar");
        tb_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_cerrarActionPerformed(evt);
            }
        });
        jPanel1.add(tb_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_abrirActionPerformed

        JFileChooser jf = new JFileChooser();
        jf.showOpenDialog(this);
        File file = jf.getSelectedFile();
        if (file != null) {
            tf_rutaa.setText(file.getAbsolutePath());
//-----

            Sax sax = new Sax();

            try {

                //  sax.setparset(String.valueOf(file));
                jt_area.setText(sax.setparset(String.valueOf(file)));

            } catch (Exception ex) {
                Logger.getLogger(LecturaSinParametros.class.getName()).log(Level.SEVERE, null, ex);

                JOptionPane.showMessageDialog(null, "Por favor, revisa el archivo que concuerde");
            }

        }


    }//GEN-LAST:event_jb_abrirActionPerformed

    private void tf_rutaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rutaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_rutaaActionPerformed

    private void tb_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_inicioActionPerformed
        // TODO add your handling code here:

        DOMGUI bnh = new DOMGUI();
        bnh.setVisible(true);
        dispose();
    }//GEN-LAST:event_tb_inicioActionPerformed

    private void tb_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_cerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tb_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAXGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAXGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAXGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAXGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAXGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_abrir;
    private javax.swing.JTextArea jt_area;
    private javax.swing.JButton tb_cerrar;
    private javax.swing.JButton tb_inicio;
    private javax.swing.JTextField tf_rutaa;
    // End of variables declaration//GEN-END:variables
}
