/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package insertDOM;

import ClaseDOM.DOM;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import mainGUI.DOMGUI;

/**
 *
 * @author oscartabora
 */
public class InsertDOM extends javax.swing.JFrame {

    /**
     * Creates new form InsertDOM
     */
    public InsertDOM() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tb_cerrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tb_inicio = new javax.swing.JButton();
        jt_id = new javax.swing.JTextField();
        jt_marca = new javax.swing.JTextField();
        jt_modelo = new javax.swing.JTextField();
        jt_cilindrada = new javax.swing.JTextField();
        tb_abrir = new javax.swing.JButton();
        tf_ruta = new javax.swing.JTextField();
        jl_correcto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Insertar elementos XML con DOM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        tb_cerrar.setText("Cerrar");
        tb_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_cerrarActionPerformed(evt);
            }
        });
        jPanel1.add(tb_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 22, 110, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 40, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Marca");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Modelo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Cilindrada");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        tb_inicio.setText("Inicio");
        tb_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_inicioActionPerformed(evt);
            }
        });
        jPanel1.add(tb_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 30));

        jt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_idActionPerformed(evt);
            }
        });
        jPanel1.add(jt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 190, 40));

        jt_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_marcaActionPerformed(evt);
            }
        });
        jPanel1.add(jt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 190, 40));

        jt_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_modeloActionPerformed(evt);
            }
        });
        jPanel1.add(jt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 190, 40));

        jt_cilindrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_cilindradaActionPerformed(evt);
            }
        });
        jPanel1.add(jt_cilindrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 190, 40));

        tb_abrir.setText("Selecione el archivo");
        tb_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_abrirActionPerformed(evt);
            }
        });
        jPanel1.add(tb_abrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 180, 40));

        tf_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rutaActionPerformed(evt);
            }
        });
        jPanel1.add(tf_ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 270, 40));

        jl_correcto.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jl_correcto.setForeground(new java.awt.Color(102, 102, 255));
        jPanel1.add(jl_correcto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, 350, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_cerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tb_cerrarActionPerformed

    private void tb_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_inicioActionPerformed
        // TODO add your handling code here:

        DOMGUI bnh = new DOMGUI();
        bnh.setVisible(true);
        dispose();

    }//GEN-LAST:event_tb_inicioActionPerformed

    private void jt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_idActionPerformed

    private void jt_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_marcaActionPerformed

    private void jt_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_modeloActionPerformed

    private void jt_cilindradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_cilindradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_cilindradaActionPerformed

    private void tb_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_abrirActionPerformed
        // TODO add your handling code here:

        String id = this.jt_id.getText().toString();
        String marca = this.jt_marca.getText().toString();
        String modelo = this.jt_modelo.getText().toString();
        String cilindrada = this.jt_cilindrada.getText().toString();
        
        String correcto = "Datos añadidos correctamente";
        
        JFileChooser jf = new JFileChooser();
        jf.showOpenDialog(this);
        File file = jf.getSelectedFile();
        if (file != null) {
            tf_ruta.setText(file.getAbsolutePath());
            //-----

            DOM dom = new DOM();
            
            try {
                dom.sertAgregar(String.valueOf(file), id, marca, modelo, cilindrada);
                
                jl_correcto.setText(correcto);
                
            } catch (Exception ex) {
                
                JOptionPane.showMessageDialog(null, "Por favor, revisa el archivo");
            }
            
        }
    }//GEN-LAST:event_tb_abrirActionPerformed

    private void tf_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_rutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertDOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertDOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertDOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertDOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertDOM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl_correcto;
    private javax.swing.JTextField jt_cilindrada;
    private javax.swing.JTextField jt_id;
    private javax.swing.JTextField jt_marca;
    private javax.swing.JTextField jt_modelo;
    private javax.swing.JButton tb_abrir;
    private javax.swing.JButton tb_cerrar;
    private javax.swing.JButton tb_inicio;
    private javax.swing.JTextField tf_ruta;
    // End of variables declaration//GEN-END:variables
}
