/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package borrarNodoHijoGUI;

import ClaseDOM.DOM;
import mainGUI.DOMGUI;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author oscartabora
 */
public class BorrarNodoHijo extends javax.swing.JFrame {

    /**
     * Creates new form BorrarNodoHijo
     */
    public BorrarNodoHijo() {
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_etiqueta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tb_abrir = new javax.swing.JButton();
        tf_ruta = new javax.swing.JTextField();
        jl_correcto = new javax.swing.JLabel();
        tb_inicio = new javax.swing.JButton();
        tb_cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Eliminación de Nodo Hija");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_idActionPerformed(evt);
            }
        });
        jPanel1.add(jt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 190, 40));

        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Nombre etiqueta hija");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jt_etiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_etiquetaActionPerformed(evt);
            }
        });
        jPanel1.add(jt_etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 190, 40));

        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("ID de coche");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 90, 30));

        tb_abrir.setText("Abrir Ruta");
        tb_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_abrirActionPerformed(evt);
            }
        });
        jPanel1.add(tb_abrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 120, 30));

        tf_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rutaActionPerformed(evt);
            }
        });
        jPanel1.add(tf_ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 270, 40));

        jl_correcto.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jl_correcto.setForeground(new java.awt.Color(102, 102, 255));
        jPanel1.add(jl_correcto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 350, 100));

        tb_inicio.setText("Inicio");
        tb_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_inicioActionPerformed(evt);
            }
        });
        jPanel1.add(tb_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        tb_cerrar.setText("Cerrar");
        tb_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_cerrarActionPerformed(evt);
            }
        });
        jPanel1.add(tb_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_idActionPerformed

    private void jt_etiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_etiquetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_etiquetaActionPerformed

    private void tb_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_abrirActionPerformed
        // TODO add your handling code here:

        String eliminacion = "Eliminacion Correcta";

        //1).Convierto los widget en texto para poder manipular
        String id = this.jt_id.getText().toString();
        String etiqueta = this.jt_etiqueta.getText().toString();

        //2).Creo un object de tipo JFileChooser, con 
        //Este object cerare una ventata donde tendre que selecinar el archivo XML.
        JFileChooser jf = new JFileChooser();
        jf.showOpenDialog(this);

        //3).Creo un object de tipo File que luego usare para un metodo de la clase DOM
        File file = jf.getSelectedFile();

        //4).Minetras lo que se vaya a selecionar no corresponda a un archivo 
        //entrata el else que enviara un mensaje de error.
        if (file != null) {
            tf_ruta.setText(file.getAbsolutePath());

            //5).Creo un object de la clase DOM
            DOM dom = new DOM();

            try {

                //6).Añado el un id(n) y el nombre de la etiqueta hija (coche) para eliminar
                dom.buscarYEliminar(id, file, etiqueta);

                //7.Imprimo un mensaje si la eliminacion fue correcta.
                jl_correcto.setText(eliminacion);

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, "Por favor, revisa el archivo");
            }

        }

    }//GEN-LAST:event_tb_abrirActionPerformed

    private void tf_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_rutaActionPerformed

    private void tb_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_inicioActionPerformed
        // TODO add your handling code here:

        DOMGUI bnh = new DOMGUI();
        bnh.setVisible(true);
        dispose();


    }//GEN-LAST:event_tb_inicioActionPerformed

    private void tb_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_cerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_tb_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrarNodoHijo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrarNodoHijo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrarNodoHijo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrarNodoHijo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrarNodoHijo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl_correcto;
    private javax.swing.JTextField jt_etiqueta;
    private javax.swing.JTextField jt_id;
    private javax.swing.JButton tb_abrir;
    private javax.swing.JButton tb_cerrar;
    private javax.swing.JButton tb_inicio;
    private javax.swing.JTextField tf_ruta;
    // End of variables declaration//GEN-END:variables
}
